#PointCloudFilter node params
axalta/ccscore/paintjobprocess/filter/voxel_leaf_size : 0.001
axalta/ccscore/paintjobprocess/filter/statfilter_meank : 180 #180
axalta/ccscore/paintjobprocess/filter/statfilter_stddev: 0.8 # 0.8 0.7 1.2 0.9 1.5 1.3
axalta/ccscore/paintjobprocess/filter/min_depth : 0.5
axalta/ccscore/paintjobprocess/filter/max_depth : 1.73
#SurfaceModelling node params
axalta/ccscore/paintjobprocess/surface/cpu_threads : 6
axalta/ccscore/paintjobprocess/surface/mls_polynomial_order : 3
axalta/ccscore/paintjobprocess/surface/mls_search_radius : 0.5 #0.9
axalta/ccscore/paintjobprocess/surface/normal_search_radius : 0.05
#Pathplanner node params
axalta/ccscore/paintjobprocess/pathplanner/number_of_points_per_row_thr : 25
axalta/ccscore/paintjobprocess/pathplanner/top_index_row_dist : 0.15 #6 inches
axalta/ccscore/paintjobprocess/pathplanner/index_pilot_row_dist : 0.05 #5 cm
#axalta/ccscore/paintjobprocess/pathplanner/bottom_index_row_dist : 0.0762 #3 inches
axalta/ccscore/paintjobprocess/pathplanner/bottom_index_row_dist : 0.05 #3 inches
axalta/ccscore/paintjobprocess/pathplanner/rowThreshold_buff : 0.0127 #3 cm
/axalta/ccscore/paintjobprocess/pathplanner/index_width : 0.035 #2.5 cm
axalta/ccscore/paintjobprocess/pathplanner/pointThreshold : 0.18 #22 cm






